"""empty message

Revision ID: 1d7741b54b45
Revises: 36f300108e31
Create Date: 2022-08-02 11:19:09.359096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7741b54b45'
down_revision = '36f300108e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'recipe_id')
    # ### end Alembic commands ###
