"""empty message

Revision ID: 44a234e3b24e
Revises: ed862d3dac1b
Create Date: 2022-08-02 10:08:25.484941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a234e3b24e'
down_revision = 'ed862d3dac1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('favorite', sa.Boolean(), nullable=True))
    op.add_column('recipe', sa.Column('menu_date', sa.String(), nullable=True))
    op.drop_column('user', 'favorite')
    op.drop_column('user', 'menu_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('menu_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('favorite', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('recipe', 'menu_date')
    op.drop_column('recipe', 'favorite')
    # ### end Alembic commands ###
