"""empty message

Revision ID: 9f33f0ad0c36
Revises: 1d7741b54b45
Create Date: 2022-08-02 11:25:22.506307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f33f0ad0c36'
down_revision = '1d7741b54b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_recipe_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'recipe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_recipe_id_fkey', 'user', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
